apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geth-fork
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: geth-fork
    spec:
      containers:
      - name: geth-fork
        image: arachnid/geth:v1.4.12
        args: [ "--fast", "--rpc", "--rpcaddr=0.0.0.0", "--rpccorsdomain=*", "--support-dao-fork" ]
        ports:
        - containerPort: 30303
        - containerPort: 8545
        readinessProbe:
          exec:
            command: [ "/readiness.sh" ]
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 30
        livenessProbe:
          exec:
            command: [ "/health.sh" ]
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 30
