apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geth-old
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: geth-old
    spec:
      containers:
      - name: geth-old
        image: arachnid/geth:v1.4.9
        args: [ "--fast", "--rpc", "--rpcaddr=0.0.0.0", "--rpccorsdomain=*" ]
        ports:
        - containerPort: 30303
        - containerPort: 8545
